spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    jackson:
        property-naming-strategy: SNAKE_CASE

custom:
    rest-service:
        services:
            default:
                ttl: 0
                retries: 0
