spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
    jpa:
        hibernate:
            ddl-auto: create

custom:
    rest-service:
        services:
            percentage:
                retries: 3
    cache-service:
        services:
            percentage:
                ttl: 30
    rate-limit-service:
        max-rpm: 3
