server:
    error:
        include-message: always

spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    jackson:
        property-naming-strategy: SNAKE_CASE

custom:
    rest-service:
        services:
            default:
                retries: 0
    cache-service:
        services:
            default:
                ttl: 0
