spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    jackson:
        property-naming-strategy: SNAKE_CASE
